server:
  port: 9091
spring:
  application:
    name: consumer-service
eureka:
  client:
#    register-with-eureka: false
    #拉取注册信息的间隔时长
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #,http://localhost:8762/eureka/

#feign默认对hystrix集成，默认情况下是关闭的，需要通过参数开启
feign:
  hystrix:
    enabled: true
#hystrix打断点超时发生熔断
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000