server:
  port: 9090
spring:
  application:
    name: provider-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hjj?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: huang994
mybatis:
  type-aliases-package: cn.hjj.user.pojo.entity
  mapper-locations: classpath*:mapper/*Mapper.xml
eureka:
  instance:
    hostname: provider01
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}-${}:${server.port}
  client:
    service-url:
      #      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
      #      向以下注册中心注册
      defaultZone: http://localhost:8761/eureka/
      #,http://localhost:8762/eureka/

